name = "scoreboard_server"
version = "0.1.0"
target = "erlang"

[dependencies]
envoy = ">= 1.2.0 and < 2.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"
global_value = ">= 1.0.0 and < 2.0.0"
libero = ">= 6.0.0 and < 7.0.0"
logging = ">= 1.3.0 and < 2.0.0"
lustre = ">= 5.7.0 and < 7.0.0"
mist = ">= 6.0.0 and < 7.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
birdie = ">= 2.0.0 and < 3.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
glinter = ">= 2.19.0 and < 3.0.0"
marmot = "1.7.1"

[tools.glinter]
stats = true
warnings_as_errors = false

[tools.marmot]
database = "db/scoreboard.db"
sql_dir = "src/server/sql"
output = "src/generated/sql/server"
