name = "scoreboard_shared"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
lustre = ">= 5.7.0 and < 7.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glinter = ">= 2.19.0 and < 3.0.0"

[tools.glinter]
stats = true
warnings_as_errors = false
scan_paths = ["../client/src", "../server/src"]
